### ISSUE TITLE
Need to add installation of jq to install instructions

### ISSUE THREAD

**Issue by mattyjacks** [januusio/cryptowallet_risk_scoring#2]
This is what I had to do to get the Google colab to work

!git clone https://github.com/januusio/cryptowallet_risk_scoring.git
!git clone https://github.com/stedolan/jq.git
%cd cryptowallet_risk_scoring
!python3 setup.py install
!pip3 install -r requirements.txt
!apt-get update
!apt-get install python3-pip
!apt-get install autoconf libtool dh-autoreconf
!pip install jq
# !pip install pyjq #may not be necessary
!apt-get install jq
!python3 example_default.py

JQ is necessary to get it to run. I think you have to add to the install instructions to install JQ

https://github.com/stedolan/jq

That's the jq github

**Comment by afrkciymjt** [comment]
https://stedolan.github.io/jq/download/

I think installing jq is fairly googleable, but we could include a link in the readme

**Comment by mattyjacks** [comment]
Yeah, I think I had to do apt-get or something rather than pip to install it
